version: '3.3'

services:
  stability-ai:
    container_name: sd
    ports:
      - '5000:5000'
    image: 'r8.im/stability-ai/stable-diffusion@sha256:be04660a5b93ef2aff61e3668dedb4cbeb14941e62a3fd5998364a32d613e35e'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  stable-diffusion-ui:
    container_name: sd-ui
    ports:
      - '9000:9000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - stability-ai

  stable-diffusion-old-port-redirect:
    container_name: sd-old-port-redirect
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: OldPortDockerfile
    volumes:
      - .:/app

networks:
  default: